# Generated by Django 6.0.1 on 2026-02-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_metricweight_factor_alter_metricweight_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='f_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Finance Head'),
        ),
        migrations.AddField(
            model_name='project',
            name='m_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marketing Head'),
        ),
        migrations.AddField(
            model_name='project',
            name='m_lead',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marketing Lead'),
        ),
        migrations.AddField(
            model_name='project',
            name='p_exec',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Executive'),
        ),
        migrations.AddField(
            model_name='project',
            name='p_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Head'),
        ),
        migrations.AddField(
            model_name='project',
            name='p_mgr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Purchase Manager'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='default_threshold',
            field=models.FloatField(default=0.0, help_text='Target value for success (e.g. 1.0 for binary tasks).'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='field_name',
            field=models.CharField(help_text='Must match a field in the Project model exactly.', max_length=100),
        ),
        migrations.AlterField(
            model_name='metricweight',
            name='factor',
            field=models.IntegerField(choices=[(1, '1 - Minimal'), (2, '2 - Very Low'), (3, '3 - Low'), (4, '4 - Low-Medium'), (5, '5 - Medium (Standard)'), (6, '6 - Medium-High'), (7, '7 - High'), (8, '8 - Very High'), (9, '9 - Critical'), (10, '10 - Maximum Priority')], default=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_3d',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_dh',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DH'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_dm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_csc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CSC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cluster/BU Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_mep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MEP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_om',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SOM/OM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_pm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SPM/PM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_ss',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_code',
            field=models.CharField(help_text='Unique Identifier (e.g. FS-MUM-001)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_head',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_lead',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Lead'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sbu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Region/SBU'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project Stage'),
        ),
    ]
