# Generated by Django 6.0.1 on 2026-01-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='no_plans_for_key_spaces',
            field=models.FloatField(default=0),
        ),
    ]
