# Generated by Django 6.0.1 on 2026-02-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_department_usergroup_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='credit_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
