# Generated by Django 6.0.1 on 2026-02-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_successmetric_remove_metric_success_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='successmetric',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue (Primary)'), ('secondary', 'Grey (Secondary)'), ('success', 'Green (Success)'), ('danger', 'Red (Danger)'), ('warning', 'Yellow (Warning)'), ('info', 'Cyan (Info)'), ('light', 'White (Light)'), ('dark', 'Black (Dark)')], default='secondary', max_length=20),
        ),
    ]
