# Generated by Django 6.0.1 on 2026-01-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('sbu', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('login_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('sales_head', models.TextField(blank=True, default='')),
                ('sales_lead', models.TextField(blank=True, default='')),
                ('design_dh', models.TextField(blank=True, default='')),
                ('design_dm', models.TextField(blank=True, default='')),
                ('design_id', models.TextField(blank=True, default='')),
                ('design_3d', models.TextField(blank=True, default='')),
                ('ops_head', models.TextField(blank=True, default='')),
                ('ops_pm', models.TextField(blank=True, default='')),
                ('ops_om', models.TextField(blank=True, default='')),
                ('ops_ss', models.TextField(blank=True, default='')),
                ('req_uploaded', models.FloatField(default=0)),
                ('site_visit_report', models.FloatField(default=0)),
                ('client_access', models.FloatField(default=0)),
                ('boq_uploaded', models.FloatField(default=0)),
                ('contract_uploaded', models.FloatField(default=0)),
                ('furniture_layouts', models.FloatField(default=0)),
                ('approved_layouts', models.FloatField(default=0)),
                ('other_layouts', models.FloatField(default=0)),
                ('mapped_spaces', models.FloatField(default=0)),
                ('key_plans_ratio', models.FloatField(default=0)),
                ('renders', models.FloatField(default=0)),
                ('approved_renders', models.FloatField(default=0)),
                ('td_elevations', models.FloatField(default=0)),
                ('cad_files', models.FloatField(default=0)),
                ('slides_download', models.FloatField(default=0)),
                ('material_deck', models.FloatField(default=0)),
                ('gfc_download', models.FloatField(default=0)),
                ('client_visit_des', models.FloatField(default=0)),
                ('site_images', models.FloatField(default=0)),
                ('invoices', models.FloatField(default=0)),
                ('mep_drawings', models.FloatField(default=0)),
                ('handover_docs', models.FloatField(default=0)),
                ('wpr_half_week', models.FloatField(default=0)),
                ('wpr_download', models.FloatField(default=0)),
                ('wpr_shared', models.FloatField(default=0)),
                ('weekly_tasks', models.FloatField(default=0)),
                ('daily_tasks', models.FloatField(default=0)),
                ('manpower_ratio', models.FloatField(default=0)),
                ('dpr_ratio', models.FloatField(default=0)),
                ('manpower_day_ratio', models.FloatField(default=0)),
                ('grn_created', models.FloatField(default=0)),
                ('grn_approved', models.FloatField(default=0)),
            ],
        ),
    ]
