# Generated by Django 6.0.1 on 2026-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_status_project_boq_project_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ops_csc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_mep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
