# Generated by Django 6.0.1 on 2026-02-06 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_ops_csc_project_ops_mep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('field_name', models.CharField(help_text='Must match a field in the Project model exactly (e.g., key_plans_ratio)', max_length=100)),
                ('stage', models.CharField(choices=[('Pre', 'Pre-Stage'), ('Post', 'Post-Stage')], max_length=10)),
                ('default_threshold', models.FloatField(default=0.0)),
                ('success_category', models.CharField(choices=[('COMPLETENESS', 'Completeness'), ('TIME', 'Time Adherence'), ('ENGAGEMENT', 'Engagement')], default='COMPLETENESS', max_length=20)),
                ('is_manual_credit', models.BooleanField(default=False)),
                ('credit_weight', models.FloatField(default=0.0, editable=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('visible_to_groups', models.ManyToManyField(blank=True, to='core.usergroup')),
            ],
        ),
    ]
