# Generated by Django 6.0.1 on 2026-02-10 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_metric_credit_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='secondary', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='metric',
            name='success_category',
        ),
        migrations.AddField(
            model_name='metric',
            name='success_metric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.successmetric'),
        ),
    ]
