# Generated by Django 6.0.1 on 2026-02-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_successmetric_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Sales', 'Sales'), ('Design', 'Design'), ('Operations', 'Operations'), ('Marketing', 'Marketing'), ('Purchase', 'Purchase'), ('Finance', 'Finance')], max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('metric_key', models.CharField(max_length=100)),
                ('factor', models.IntegerField(choices=[(1, '1 - Low Impact (Standard Task)'), (2, '2 - Medium Impact'), (3, '3 - High Impact'), (4, '4 - Very High Impact'), (5, '5 - Critical (Make or Break)')], default=1, help_text='Select the importance of this metric for this role.')),
            ],
            options={
                'unique_together': {('role', 'metric_key')},
            },
        ),
    ]
