# Generated by Django 6.0.1 on 2026-02-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_metricweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricweight',
            options={'verbose_name': 'Metric Weight', 'verbose_name_plural': 'Metric Weights'},
        ),
        migrations.AlterUniqueTogether(
            name='metricweight',
            unique_together={('department', 'role', 'metric_key')},
        ),
        migrations.AlterField(
            model_name='metricweight',
            name='factor',
            field=models.IntegerField(choices=[(1, '1 - Low Impact (Standard Task)'), (2, '2 - Medium Impact'), (3, '3 - High Impact'), (4, '4 - Very High Impact'), (5, '5 - Critical (Make or Break)')], default=1, help_text='Relative Weight (1=Low, 5=Critical)'),
        ),
    ]
