# Generated by Django 6.0.1 on 2026-02-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_metric_credit_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetricWeight',
        ),
        migrations.AddField(
            model_name='metric',
            name='credit_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='metric',
            name='is_manual_credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_renders',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='boq',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='cad_files',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='client_access',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='client_visit_des',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='daily_tasks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='design_3d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='design_dh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='design_dm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='dpr_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gfc_download',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='grn_approved',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='grn_created',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='handover_docs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='invoices',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='key_plans_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='manpower_day_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='manpower_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='mapped_spaces',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='material_deck',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='mep_drawings',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='no_plans_for_key_spaces',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_csc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_head',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_mep',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_om',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_pm',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='ops_ss',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='other_layouts',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='renders',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='sales_lead',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='site_images',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='site_visit_report',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='slides_download',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='td_elevations',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='weekly_tasks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='wpr_download',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='wpr_half_week',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='wpr_shared',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='field_name',
            field=models.CharField(help_text='Must match a field in the Project model exactly (e.g., key_plans_ratio)', max_length=100),
        ),
        migrations.AlterField(
            model_name='successmetric',
            name='color',
            field=models.CharField(choices=[('primary', 'Blue (Primary)'), ('secondary', 'Grey (Secondary)'), ('success', 'Green (Success)'), ('danger', 'Red (Danger)'), ('warning', 'Yellow (Warning)'), ('info', 'Cyan (Info)'), ('light', 'White (Light)'), ('dark', 'Black (Dark)')], default='secondary', max_length=20),
        ),
    ]
