# Generated by Django 6.0.1 on 2026-02-11 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_metricweight_metric_credit_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='credit_weight',
        ),
        migrations.RemoveField(
            model_name='metric',
            name='is_manual_credit',
        ),
        migrations.CreateModel(
            name='MetricWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.IntegerField(choices=[(1, '1 - Minimal'), (2, '2 - Very Low'), (3, '3 - Low'), (4, '4 - Low-Medium'), (5, '5 - Medium (Standard)'), (6, '6 - Medium-High'), (7, '7 - High'), (8, '8 - Very High'), (9, '9 - Critical'), (10, '10 - Maximum Priority')], default=5, help_text='Importance relative to other tasks for THIS group.')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='core.metric')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usergroup')),
            ],
            options={
                'verbose_name': 'Group Weight',
                'unique_together': {('metric', 'user_group')},
            },
        ),
    ]
