# Generated by Django 6.0.1 on 2026-02-11 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_metric_credit_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricweight',
            name='factor',
            field=models.IntegerField(choices=[(1, '1 - Minimal'), (2, '2 - Very Low'), (3, '3 - Low'), (4, '4 - Low-Medium'), (5, '5 - Medium (Standard)'), (6, '6 - Medium-High'), (7, '7 - High'), (8, '8 - Very High'), (9, '9 - Critical'), (10, '10 - Maximum Priority')], default=1, help_text='Importance relative to other tasks for THIS group.'),
        ),
        migrations.AlterField(
            model_name='metricweight',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.metric'),
        ),
    ]
