# Generated by Django 6.0.1 on 2026-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_project_f_head_project_m_head_project_m_lead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='max_threshold',
            field=models.FloatField(default=10.0, help_text='Maximum points achievable for this metric.'),
        ),
        migrations.AddField(
            model_name='metric',
            name='min_threshold',
            field=models.FloatField(default=0.0, help_text='Below this value, score is 0.'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='default_threshold',
            field=models.FloatField(default=1.0, verbose_name='Legacy Target'),
        ),
    ]
