# Generated by Django 6.0.1 on 2026-02-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_metric_max_threshold_metric_min_threshold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metric',
            name='default_threshold',
        ),
    ]
