# Generated by Django 6.0.1 on 2026-02-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_metric_default_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='floors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lead_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wpr_ratio',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='min_threshold',
            field=models.FloatField(default=1.0, help_text='Below this value, score is 0.'),
        ),
    ]
