# Generated by Django 6.0.1 on 2026-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_floors_project_lead_id_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='days_till_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='manpower_added_days',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='weeks_till_date',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='project',
            name='wpr_download_weeks',
            field=models.FloatField(default=0.0),
        ),
    ]
