# Generated by Django 6.0.1 on 2026-02-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_days_till_date_project_manpower_added_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='design_3d',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='3D'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_dh',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='DH'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_dm',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='DM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='f_head',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Finance Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='m_head',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Marketing Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='m_lead',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Marketing Lead'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_csc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='CSC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_head',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Cluster/BU Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_mep',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MEP'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_om',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SOM/OM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_pm',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SPM/PM'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ops_ss',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='SS'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_exec',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Purchase Executive'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_head',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Purchase Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_mgr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Purchase Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_head',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sales Head'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sales_lead',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sales Lead'),
        ),
    ]
